-- MySQL Script generated by MySQL Workbench
-- Sun Jan 10 18:32:39 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema veiculos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema veiculos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `veiculos` DEFAULT CHARACTER SET latin1 ;
USE `veiculos` ;

-- -----------------------------------------------------
-- Table `veiculos`.`carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veiculos`.`carro` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(25) NOT NULL,
  `marca` VARCHAR(25) NOT NULL,
  `ano` INT(4) NOT NULL,
  `placa` VARCHAR(12) NOT NULL,
  `nomeProprietario` VARCHAR(32) NULL DEFAULT NULL,
  `endereco` VARCHAR(50) NULL DEFAULT NULL,
  `dataNascimento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `placa` (`placa` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
